version: 2
updates:
  # Root workspace dependencies
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "sunday"
    open-pull-requests-limit: 5
    commit-message:
      prefix: "chore"
      prefix-development: "chore(dev)"
      
  # Frontend app dependencies
  - package-ecosystem: "npm"
    directory: "/apps/frontend"
    schedule:
      interval: "weekly"
      day: "sunday"
    open-pull-requests-limit: 3
    commit-message:
      prefix: "chore(frontend)"
      
  # Backend app dependencies
  - package-ecosystem: "npm"
    directory: "/apps/backend"
    schedule:
      interval: "weekly"
      day: "sunday"
    open-pull-requests-limit: 3
    commit-message:
      prefix: "chore(backend)"
      
  # GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"
    commit-message:
      prefix: "ci"
