name: CI Simple (No Database)

on:
  push:
    branches: [ main, dev, feature/* ]
  pull_request:
    branches: [ main, dev ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        node-version: [18, 20]
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Install pnpm
        uses: pnpm/action-setup@v3
        with:
          version: 8
          run_install: false
      
      - name: Setup Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'pnpm'
      
      - name: Get pnpm store directory
        id: pnpm-cache
        run: |
          echo "STORE_PATH=$(pnpm store path)" >> $GITHUB_OUTPUT
      
      - name: Setup pnpm cache
        uses: actions/cache@v4
        with:
          path: ${{ steps.pnpm-cache.outputs.STORE_PATH }}
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-
      
      - name: Install dependencies
        run: pnpm install --frozen-lockfile
      
      - name: Run linting
        run: |
          echo "::group::Backend Lint"
          pnpm --filter @saas-chat/backend lint || true
          echo "::endgroup::"
          echo "::group::Frontend Lint"  
          pnpm --filter @saas-chat/frontend lint || true
          echo "::endgroup::"
      
      - name: Build packages
        run: |
          echo "::group::Build Backend"
          pnpm --filter @saas-chat/backend build
          echo "::endgroup::"
          echo "::group::Build Frontend"
          pnpm --filter @saas-chat/frontend build
          echo "::endgroup::"
      
      - name: Upload backend build artifacts
        uses: actions/upload-artifact@v4
        if: matrix.node-version == '20'
        with:
          name: backend-dist
          path: apps/backend/dist
          retention-days: 1
      
      - name: Upload frontend build artifacts
        uses: actions/upload-artifact@v4
        if: matrix.node-version == '20'
        with:
          name: frontend-dist
          path: apps/frontend/dist
          retention-days: 1
      
      - name: Summary
        run: |
          echo "## Build Summary" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "- ✅ Node version: ${{ matrix.node-version }}" >> $GITHUB_STEP_SUMMARY
          echo "- ✅ Dependencies installed" >> $GITHUB_STEP_SUMMARY
          echo "- ✅ Backend built successfully" >> $GITHUB_STEP_SUMMARY
          echo "- ✅ Frontend built successfully" >> $GITHUB_STEP_SUMMARY
